language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
before_script:
  - npm install -g bower
  - bower install
  - psql -c 'create database snada_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp .env.example .env
