require "rails_helper"

RSpec.describe ContactNotifier, type: :mailer do
  let(:subject) {
    "subject"
  }

  let(:from) {
    "test@rspec.com"
  }

  let(:body) {
    "This mail was autogenerated by rspec"
  }

  describe "contact_mail" do
    it "should send a contact email" do
      email = ContactNotifier.contact_mail(subject, from, body).deliver_now
      expect(ActionMailer::Base.deliveries.empty?).to be false
    end

    it "should clearly state in the subject where does it come from" do
      email = ContactNotifier.contact_mail(subject, from, body).deliver_now
      expect(email.subject).to eq("[SNADA CONTACT FORM] #{subject}")
    end

    it "should have the correct from if present" do
      email = ContactNotifier.contact_mail(subject, from, body).deliver_now
      expect(email.from).to eq([from])
    end

    it "should have the default from if not present" do
      email = ContactNotifier.contact_mail(subject, '', body).deliver_now
      expect(email.from).to eq([ENV['PERSONAL_MAIL']])
    end

    it "should be sent to my personal inbox" do
      email = ContactNotifier.contact_mail(subject, '', body).deliver_now
      expect(email.to).to eq([ENV['PERSONAL_MAIL']])
    end

    it "should contain the passed body" do
      email = ContactNotifier.contact_mail(subject, from, body).deliver_now
      expect(email.body.encoded).to include(subject)
    end
  end
end
